In [4]:
import numpy as np
arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])
arr = np.nan_to_num(arr, nan=0)
print("After replacing NaN with 0:")
print(arr)
arr_transpose = arr.T
print("\nAfter interchanging rows and columns:")
print(arr_transpose)

After replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [3]:
import numpy as np
arr = np.arange(24).reshape(2, 3, 4)
print("Original Shape:", arr.shape)
new_arr = np.moveaxis(arr, 0, 2)
print("New Shape:", new_arr.shape)
print(new_arr)

Original Shape: (2, 3, 4)
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [2]:
import numpy as np

arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
col_mean = np.nanmean(arr, axis=0)
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])
print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [1]:
import numpy as np
arr = np.array([10, -5, 20, -8, 15])
arr[arr < 0] = 0
print(arr)

[10  0 20  0 15]
