In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6]])
combined = np.vstack((arr1, arr2))
print(combined)

[[1 2 3]
 [4 5 6]]


In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [4]:
arr = np.array([10, 20, 30, 40, 50])
reversed_arr = arr[::-1]
print(reversed_arr)

[50 40 30 20 10]


In [5]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Maximum =", np.max(arr))
print("Minimum =", np.min(arr))
rows, cols = arr.shape
print("Rows =", rows)
print("Columns =", cols)

Maximum = 6
Minimum = 1
Rows = 2
Columns = 3


In [6]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
print("Entire Array:")
print(arr)
print("Element at row 1 column 2:")
print(arr[1, 2])
print("First Row:")
print(arr[0])
print("Second Column:")
print(arr[:, 1])

Entire Array:
[[10 20 30]
 [40 50 60]]
Element at row 1 column 2:
60
First Row:
[10 20 30]
Second Column:
[20 50]


In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
total = 0
for row in arr:
    for element in row:
        total += element
print("Sum =", total)

Sum = 21


In [8]:
a = np.array([4, 5, 6])
b = np.array([1, 2, 3])
print("Addition : ",a + b)
print("Subtraction : ",a - b)
print("Multiplication : ",a * b)
print("Division : ",a / b)

Addition :  [5 7 9]
Subtraction :  [3 3 3]
Multiplication :  [ 4 10 18]
Division :  [4.  2.5 2. ]


In [9]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
for block in arr:
    for row in block:
        for element in row:
            print(element)

1
2
3
4
5
6
7
8


In [10]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [11]:
from scipy import stats
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])
avg_array = (arr1 + arr2) / 2
print("Average Array:")
print(avg_array)
combined = np.concatenate((arr1.flatten(),
                           arr2.flatten()))
print("\nCombined Array:")
print(combined)

mean_value = np.mean(combined)
print("Mean =", mean_value)

median_value = np.median(combined)
print("Median =", median_value)

mode_value = stats.mode(combined, keepdims=True)

print("Mode =", mode_value.mode[0])

Average Array:
[[3. 4.]
 [5. 6.]]

Combined Array:
[1 2 3 4 5 6 7 8]
Mean = 4.5
Median = 4.5
Mode = 1
